# Generated by Django 4.1.1 on 2023-01-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_reviews_category_delete_reviews1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='category',
        ),
    ]
