# Generated by Django 4.1.1 on 2023-01-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_reviews1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='category',
            field=models.CharField(choices=[('верифицирован', 'верифицирован'), ('не верифицирован', 'не верифицирован')], default='не верифицирован', max_length=35),
        ),
        migrations.DeleteModel(
            name='Reviews1',
        ),
    ]
