# Generated by Django 4.1.1 on 2023-01-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_reviews_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='category',
            field=models.CharField(choices=[('не верифицирован', 'не верифицирован'), ('верифицирован', 'верифицирован')], default='не верифицирован', max_length=35),
        ),
    ]
