# Generated by Django 4.1.1 on 2022-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('второй_дом', 'второй_дом'), ('участок', 'участок'), ('баня', 'баня'), ('улица', 'улица'), ('первый_дом', 'первый_дом')], default='улица', max_length=15),
        ),
    ]
