# Generated by Django 4.1.1 on 2023-01-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('улица', 'улица'), ('второй_дом', 'второй_дом'), ('баня', 'баня'), ('первый_дом', 'первый_дом'), ('участок', 'участок')], default='улица', max_length=15),
        ),
    ]
