# Generated by Django 4.1.1 on 2023-01-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('участок', 'участок'), ('второй_дом', 'второй_дом'), ('первый_дом', 'первый_дом'), ('баня', 'баня'), ('улица', 'улица')], default='улица', max_length=15),
        ),
    ]
