# Generated by Django 4.1.1 on 2023-01-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('первый_дом', 'первый_дом'), ('улица', 'улица'), ('участок', 'участок'), ('второй_дом', 'второй_дом'), ('баня', 'баня')], default='улица', max_length=15),
        ),
    ]
